# Supported funding model platforms

# Your GitHub username or organization (if GitHub Sponsors is enabled)
github: [DiscoverTalent]

# Up to 4 custom sponsorship or support URLs:
custom: [
  'https://discover-talent-presents.com/',
  'https://discovertalent.co.in/',
  'https://discover-talent-presents.creator-spring.com/',
  'https://g.page/r/CfAeTI_4tqbyEBE/review'
]
